FROM node:22 AS build

WORKDIR /app

RUN git clone https://github.com/tommot20077/FileManagementWeb.git source && \
    cd /app/source && \
    cp -r /app/source/* /app/ && \
    mkdir -p /app/temp && \
    cp /app/source/docker/config.js /app/temp/config.js && \
    rm -rf /app/source && \
    cd /app

RUN npm install

CMD ["npm", "run", "main"]
